package com.javelin.core.model;

import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Mutation Data Model
 *
 * Holds the complete result of PITest mutation analysis:
 * - All generated mutants with their status
 * - A kill matrix mapping each test to the mutants it killed
 *
 * @param mutants    All mutants generated by PITest (KILLED, SURVIVED, NO_COVERAGE, etc.)
 * @param killMatrix Mapping of testId → set of mutantIds that the test killed
 */
public record MutationData(
        List<MutantInfo> mutants,
        Map<String, Set<String>> killMatrix
) {

    /**
     * Returns the total number of mutants generated.
     */
    public int getMutantCount() {
        return mutants.size();
    }

    /**
     * Returns the number of killed mutants (including TIMED_OUT).
     */
    public int getKilledCount() {
        return (int) mutants.stream().filter(MutantInfo::isKilled).count();
    }

    /**
     * Returns the number of survived mutants.
     */
    public int getSurvivedCount() {
        return (int) mutants.stream().filter(MutantInfo::isSurvived).count();
    }

    /**
     * Returns the number of mutants with no test coverage.
     */
    public int getNoCoverageCount() {
        return (int) mutants.stream().filter(MutantInfo::isNoCoverage).count();
    }
}
