package com.javelin.core.model;

/**
 * Mutant Info Model
 *
 * Represents a single mutant generated by PITest during mutation analysis.
 *
 * @param mutantId     Unique identifier (format: "mutatedClass:lineNumber:mutatorSuffix:index")
 * @param mutatedClass Fully qualified class name where the mutant was injected
 * @param lineNumber   Source line number of the mutant
 * @param status       PITest outcome: KILLED, SURVIVED, NO_COVERAGE, TIMED_OUT, etc.
 */
public record MutantInfo(
        String mutantId,
        String mutatedClass,
        int lineNumber,
        String status
) {

    /**
     * Returns the line key in the same format used by SpectrumMatrix: "className:lineNumber"
     */
    public String getLineKey() {
        return mutatedClass + ":" + lineNumber;
    }

    /**
     * Returns true if this mutant was killed by at least one test.
     * TIMED_OUT is treated as killed (the test detected abnormal behaviour).
     */
    public boolean isKilled() {
        return "KILLED".equals(status) || "TIMED_OUT".equals(status);
    }

    /**
     * Returns true if this mutant survived (no test detected the mutation).
     */
    public boolean isSurvived() {
        return "SURVIVED".equals(status);
    }

    /**
     * Returns true if PITest reported no test coverage for this mutant.
     */
    public boolean isNoCoverage() {
        return "NO_COVERAGE".equals(status);
    }
}
